
###
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
  "email": "riyad1@gmail.com",
  "username": "riayd",
  "password": "1234"
}

###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "abc33@gmail.com",
  "password": "1234"
}



###
GET  http://localhost:3000/api/v1/auth/logout
Content-Type: application/json


###
GET  http://localhost:3000/api/v1/contract
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiYzMzQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicmlheWQiLCJpYXQiOjE3MDQ5MTQ1ODh9.dw3FQwzgVGoMhmjQDx6-CLSx_6Evz54evvLWqtSp9-c; Path=/; HttpOnly
Content-Type: application/json; charset=utf-8