version: '3.9'
services:
  # mongodb service
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  # api service
  my-server:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    environment:
      NODE_PORT: $PORT
      HASH_SECRET: $HASH_SECRET
      JWT_SECRET: $JWT_SECRET
      MONGO_URL: mongodb://mongodb:27017
      DB_NAME: my-db
    depends_on:
      - mongodb
volumes:
  mongo_db: {}
# learning resource
# https://www.youtube.com/watch?v=vm3YfOHf_Cc&ab_channel=MafiaCodes
